export const metadata = {
  title: "About - Create Next App",
  description: "Generated by About - create next app",
};

const AboutLayout = ({ children }) => {
  return (
    <section>
      <nav className="mt-8">
        <ul className="flex gap-5">
          <li className="cursor-pointer rounded-lg px-3 py-1 bg-gray-100 hover:bg-black hover:text-white">Item-1</li>
          <li className="cursor-pointer rounded-lg px-3 py-1 bg-gray-100 hover:bg-black hover:text-white">Item-2</li>
          <li className="cursor-pointer rounded-lg px-3 py-1 bg-gray-100 hover:bg-black hover:text-white">Item-3</li>
        </ul>
      </nav>
      { children }
    </section>
  )
}

export default AboutLayout;